- name: Set up Kafka
  hosts: webservers
  tasks:

    - name: Replace HOST_1 in Kafka file
      ansible.builtin.replace:
        path: ../../../build/docker-compose.yaml
        regexp: '\{HOST_1\}'
        replace: '{{ hostvars["VM_1"]["ansible_host"] }}'

    - name: Replace HOST_2 in Kafka file
      ansible.builtin.replace:
        path: ../../../build/docker-compose.yaml
        regexp: '\{HOST_1\}'
        replace: '{{ hostvars["VM_2"]["ansible_host"] }}'

    - name: Replace HOST_3 in Kafka file
      ansible.builtin.replace:
        path: ../../../build/docker-compose.yaml
        regexp: '\{HOST_1\}'
        replace: '{{ hostvars["VM_3"]["ansible_host"] }}'
